# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


def load_countries_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "countries")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10000)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(load_countries_from_fixture),
    ]
